tool: APIScout
version: 0.1.0
generated_at: '2026-03-29T14:03:29.647768+00:00'
title: www.gtshebei.com API
stats:
  total_records: 123
  total_endpoints: 44
  confirmed: 43
  uncertain: 1
auth_type: bearer_jwt
